[package]
name = "cli_calculator"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.6.0"
chumsky = "0.11.1"
clap = { version = "4.5", features = ["derive"] }
copypasta = "0.10.2"
eframe = "0.33.0"
egui = "0.33.0"
once_cell = "1.21.3"
